id: node5
address: localhost:50055
data_dir: ./data/node4

election_timeout: 300ms
heartbeat_timeout: 100ms

peers:
  - id: node1
    address: localhost:50051

  - id: node2
    address: localhost:50052

  - id: node3
    address: localhost:50053

  - id: node4
    address: localhost:50054